### ISSUE TITLE
looks like bug in switch statement

### ISSUE THREAD

**Issue by jamerlan** [vngx/vngx-jsch#2]
java.lang.VerifyError: (class: org/vngx/jsch/userauth/UserAuthPublicKey, method: authUser signature: (Lorg/vngx/jsch/Session;[B)Z) Illegal default target in switch
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:169)
    at org.vngx.jsch.config.JSchConfig.getClassImpl(JSchConfig.java:170)
    at org.vngx.jsch.userauth.UserAuth.authenticateUser(UserAuth.java:282)
    at org.vngx.jsch.Session.connect(Session.java:272)

How I get this error:
Create ssh key with passphrase
Try to copy file to sftp using this key

**Comment by scott2449** [comment]
Closing this is the same as issue #1
